lms/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from library import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #  auth links
    path('signup/',views.signup ,name='signup'),
    path('signin/',views.signin ,name='signin'),
    path('signout/',views.signout ,name='signout'),
    # basic links
    path('', views.homepage, name='homepage'),
    path('profile', views.profile, name='profile'),
    path('404/', views.not_found, name='404'),
    # library links

    # membership links
    path('memberships/', views.membership_list, name='membership_list'),
    path('membership/create/', views.membership_create, name='membership_create'),
    path('membership/<int:membership_id>/update', views.membership_update, name='membership_update'),
    path('membership/<int:membership_id>/delete', views.membership_delete, name='membership_delete'),
    
    # members
    path('membership/<int:membership_id>/members', views.member_list, name='member_list'),
    path('member/create', views.member_create, name='member_create'),
    

    # book links
    path('books/', views.book_list, name='book_list'),
    path('book/create/', views.book_create, name='book_create'),
    path('book/<int:book_id>/', views.book_detail, name='book_detail'),
    path('book/<int:book_id>/update', views.book_update, name='book_update'),
    path('book/<int:book_id>/delete', views.book_delete, name='book_delete'),
    
    # auther links
    path('authers/', views.auther_list, name='auther_list'),
    path('auther/create/', views.auther_create, name='auther_create'),
    path('auther/<int:auther_id>/update', views.auther_update, name='auther_update'),
    path('auther/<int:auther_id>/delete', views.auther_delete, name='auther_delete'),

    # genre links
    path('genres/', views.genre_list, name='genre_list'),
    path('genre/create/', views.genre_create, name='genre_create'),
    path('genre/<int:genre_id>/update', views.genre_update, name='genre_update'),
    path('genre/<int:genre_id>/delete', views.genre_delete, name='genre_delete'),

    # log links
    path('log/', views.log_list, name='log_list'),
    path('borrow/', views.log_create, name='log_create'),
    # path('return/<int:log_id>/', views.log_update, name='log_return'),
    path('return/<int:log_id>/', views.log_return, name='log_return'),


]
# media and static links
if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator

class Library(models.Model):
    manager = models.OneToOneField(User, default=1, on_delete=models.CASCADE, related_name="library")
    name = models.CharField(max_length=120)
    description = models.TextField()
    opening_time = models.TimeField()
    closing_time = models.TimeField()
    # for the admin panel
    def __str__(self):
        return self.name
class Membership(models.Model):
    periods = (
		("M", "Monthly"),
		("Y", "Yearly"),
	)
    library = models.ForeignKey(Library, default=1, related_name='memberships', on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    period = models.CharField(max_length=1, choices=periods)
    def __str__(self):
        return self.name


class Member(models.Model):
    genders = (
        ("M", "Male"),
        ("F", "Female"),
    )
    gender = models.CharField(max_length=1, choices=genders)
    user = models.OneToOneField(User, on_delete=models.CASCADE, )
    membership = models.ForeignKey(Membership, default=1 ,on_delete=models.CASCADE, related_name="members")
    def __str__(self):
        return self.user.username

class Book(models.Model):
    name = models.CharField(max_length=191)
    auther = models.ForeignKey("Auther", on_delete=models.CASCADE, related_name="books")
    year = models.CharField(max_length=4)
    isbn = models.CharField(max_length=13, validators=[MinLengthValidator(10)], unique=True)
    cover = models.ImageField(upload_to='book_covers', null=True, blank=True)
    # if the genre is deleted set the value to null
    # many to many relationship because its gonna be many books can have many genre 
    genres = models.ManyToManyField("Genre", related_name='book')
    copies = models.IntegerField(default=1)
    library = models.ForeignKey(Library, on_delete=models.PROTECT, related_name="books")
    def __str__(self):
        return self.name
class Auther(models.Model):
    name = models.CharField(max_length=191)
    bio = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.name
class Genre(models.Model):
    name = models.CharField(max_length=191)
    def __str__(self):
        return self.name

class LibraryLog(models.Model):
    library = models.OneToOneField(Library, on_delete=models.PROTECT)
    member = models.ForeignKey(Member, on_delete=models.PROTECT)
    book = models.ForeignKey(Book, on_delete=models.PROTECT, related_name="logs")
    borrow_date = models.DateTimeField(auto_now=True)
    return_date = models.DateTimeField(null=True, blank=True)

library/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
# for sending emails to the user after she is added as a member
# from django.core.mail import send_mail
# from django.http import HttpResponse

from .forms import RegisterForm, LoginForm, LibraryForm, MembershipForm, BookForm, AutherForm, GenreForm, MemberForm, LibraryLogForm
from .models import Library, Membership, Member, Book, Auther, Genre, LibraryLog
import datetime

#####################################################################
#       basic views                                                  #
#####################################################################
def homepage(request):
    return render(request, 'homepage.html')

def not_found(request):
    return render(request, '404.html')

def profile(request):
    context = {
        "user": request.user,
    }
    return render(request,'profile.html', context)


#####################################################################
#       auth views                                                  #
#####################################################################

def signup(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(user.password)
            user.save()
            login(request, user)
            return redirect("homepage")
    context = {
        "form":form,
    }
    return render(request, 'signup.html', context)

def signin(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            auth_user = authenticate(username=username, password=password)
            if auth_user is not None:
                login(request, auth_user)
                return redirect('homepage')
    context = {
        "form":form
    }
    return render(request, 'signin.html', context)

def signout(request):
    logout(request)
    return redirect("signin")

#####################################################################
#       library views for admin and staff only                      #
#####################################################################

def library_details(request, library_id=1):
    library_obj = Library.objects.get(id=library_id)
    context = {

    }
    return render(request, 'library_details.html', context)

def library_create(request):
    # only staff can create a library
    if not request.user.is_staff:
        return redirect('404')
    
    form = LibraryForm()
    if request.method == "POST":
        form = LibraryForm(request.POST)
        if form.is_valid:
            library_obj = form.save(commit=False)
            library_obj.manager = request.user
            library_obj.save()
            return redirect('library_details', library_obj.id)
    context = {
        "form": form,
    }
    return render(request, 'library_create.html', context)

def library_update(request, library_id):
    # validate if the user is staff or if its a manager of the library
    library_obj = Library.objects.get(id=library_id)
    if not (request.user.is_staff or request.user == library_obj.owner):
        return redirect('404')

    form = LibraryForm(instance=library_obj)
    if request.method == "POST":
        form = LibraryForm(request.POST, request.FILES, instance=library_obj)
        if form.is_valid():
            form.save()
            return redirect('library_details.html')
    context = {
        "library": library_obj,
        "form":form,
    }
    return render(request, 'library_update.html', context)

def library_delete(request, library_id):
    # only staff can delete library
    if not request.user.is_staff:
        return redirect('404')
    
    library_obj = Library.objects.get(id=library_id)
    library_obj.delete()
    return redirect('')

#####################################################################
#       mempership views                                            #
#####################################################################

def membership_list(request, library_id=1):
    library = Library.objects.get(id=library_id)
    if request.user.is_staff or request.user != library.manager:
        return redirect('404')
    memberships = library.memberships.all()
    context = {
        'memberships': memberships
    }
    return render(request, 'manager/membership_list.html', context)

def membership_create(request, library_id=1):
    library = Library.objects.get(id=library_id)
    if request.user.is_staff or request.user != library.manager:
        return redirect('404')
    form = MembershipForm()
    if request.method == "POST":
        form = MembershipForm(request.POST)
        if form.is_valid:
            membership = form.save(commit=False)
            membership.library = library
            membership.save()
            return redirect('membership_list')
    context = {
        'form': form
    }
    return render(request, 'manager/membership_create.html', context)

def membership_update(request, membership_id, library_id=1):
    library = Library.objects.get(id=library_id)
    if (not request.user.is_staff) or (request.user != library.manager):
        return redirect('404')

    membership = Membership.objects.get(id=membership_id)
    if request.method == "POST":
        form = MembershipForm(instance=membership)
        if form.is_valid():
            form.save()
            return redirect('membership_list')

    context = {
        'form': form,
        'membership': membership
    }
    return render(request, 'membership_list', context)

def membership_delete(request, membership_id):
	Membership.objects.get(id=membership_id).delete()
	return redirect('membership_list')

#####################################################################
#       book views                                                  #
#####################################################################

def book_list(request, library_id=1):
    library = Library.objects.get(id=library_id)
    books = Book.objects.all()
    context = {
        'books': books
    }
    return render(request, 'book/book_list.html', context)

def book_detail(request, book_id, library_id=1):
    book = Book.objects.get(id=book_id)
    context = {
        'book': book
    }
    return render(request, 'book/book_detail.html', context)

def book_create(request, library_id=1):
    library = Library.objects.get(id=library_id)
    if request.user.is_staff or request.user != library.manager:
        return redirect('404')
    form = BookForm()
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)
        if form.is_valid:
            book = form.save(commit=False)
            book.library = library
            book.save()
            form.save_m2m()
            return redirect('book_list')
    context = {
        'form': form
    }
    return render(request, 'book/book_create.html', context)

def book_update(request, book_id, library_id=1):
    library = Library.objects.get(id=library_id)
    if request.user.is_staff or request.user != library.manager:
        return redirect('404')
    book = Book.objects.get(id=book_id)
    form = BookForm(instance=book)
    if request.method == "POST":
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save(commit=False)
            form.library = library
            form.save()
            return redirect('book_list')
    context = {
        'form': form,
        'book': book,
    }
    return render(request, 'book/book_update.html', context)

def book_delete(request, book_id, library_id=1):
    library = Library.objects.get(id=library_id)
    if request.user.is_staff or request.user != library.manager:
        return redirect('404')
    Book.objects.get(id=book_id).delete()
    return redirect('book_list')

#####################################################################
#       auther views                                                #
#####################################################################

def auther_list(request):
    authers = Auther.objects.all()
    context = {
        'authers': authers
    }
    return render(request, 'auther/auther_list.html', context)

def auther_create(request, library_id=1):
    library = Library.objects.get(id=library_id)
    if request.user.is_staff or request.user != library.manager:
        return redirect('404')
    form = AutherForm()
    if request.method == "POST":
        form = AutherForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('auther_list')
    context = {
        'form': form
    }
    return render(request, 'auther/auther_create.html', context)

def auther_update(request, auther_id, library_id=1):
    library = Library.objects.get(id=library_id)
    if (not request.user.is_staff) or (request.user != library.manager):
        return redirect('404')

    auther = Auther.objects.get(id=auther_id)
    if request.method == "POST":
        form = AutherForm(instance=auther)
        if form.is_valid():
            form.save()
            return redirect('auther_list')
    context = {
        'form': form,
        'auther': auther
    }
    return render(request, 'auther_list', context)

def auther_delete(request, auther_id):
	Auther.objects.get(id=auther_id).delete()
	return redirect('auther_list')

#####################################################################
#       genre views                                                 #
#####################################################################

def genre_list(request):
    genres = Genre.objects.all()
    context = {
        'genres': genres

library/templates/homepage.html
{% extends 'layout/base.html' %}

{% block title %}Homepage{% endblock title %}

{% block content %}
<div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
            <div class="col-lg-7">
                <div class="p-5">
                    <div class="text-center">
                        <h1><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-book-half"
                                fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                    d="M8.5 2.687v9.746c.935-.53 2.12-.603 3.213-.493 1.18.12 2.37.461 3.287.811V2.828c-.885-.37-2.154-.769-3.388-.893-1.33-.134-2.458.063-3.112.752zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z" />
                            </svg>
                            <span class="pl-3">LMS</span></h1>
                        <h1 class="h2 text-gray-900 mb-4">Are you ready to explorer new worlds!</h1>
                    </div>
                    <div class="py-5">
                        <p>Django comes with a ready and easy-to-use light engine to send e-mail. Similar to Python you
                            just need an import of smtplib. In Django you just need to import django.core.mail. To start
                            sending e-mail, edit your project settings.py file and set the following options −
                        </p>
                        <p>Django comes with a ready and easy-to-use light engine to send e-mail. Similar to Python you
                            just need an import of smtplib. In Django you just need to import django.core.mail. To start
                            sending e-mail, edit your project settings.py file and set the following options −
                        </p>
                    </div>
                    <hr class="py-3">
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'book_list' %}" class="btn btn-facebook btn-user btn-block">
                        <i class="fa fa-search fa-fw mr-3"></i>find your next book
                    </a>
                    {% else %}
                    <a href="{% url 'signup' %}" class="btn btn-primary btn-user btn-block">
                        Register Account
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

library/templates/profile.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Profile{% endblock title %}

{% block content %}
<div class="row d-flex">
    <div class="col-md-9 mx-auto">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Hello {{user}}</h6>
            </div>
            <div class="card-body">
                <div class="row my-3">
                    <div class="col-md-3">
                        <strong>Username</strong>
                    </div>
                    <div class="col-md-9">
                        <h5>{{user.username}}</h5>
                    </div>
                </div>
                <div class="row my-3">
                    <div class="col-md-3">
                        <strong>email</strong>
                    </div>
                    <div class="col-md-9">
                        <h5>{{user.email}}</h5>
                    </div>
                </div>
                <div class="row my-3">
                    <div class="col-md-3">
                        <strong>Gender</strong>
                    </div>
                    <div class="col-md-9">
                        <strong>{{user.member.gender}}</strong>
                    </div>
                </div>
                <div class="row my-3">
                    <div class="col-md-3">
                        <strong>Book History</strong>
                    </div>
                    <div class="col-md-9">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Book</th>
                                    <th>Borrow Date</th>
                                    <th>Return Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for log in user.member.librarylog_set.all %}
                                <tr>
                                    <td scope="row"> {{log.book}}</td>
                                    <td>{{log.borrow_date}}</td>
                                    <td>{{log.return_date}}</td>
                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

library/templates/signin.html
<!doctype html>
{% load static %}
{% load crispy_forms_tags %}

<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/5a4608d316.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'auth.css' %}">

    <title>LibraryMS | Register Account</title>
</head>

<body>

    <div class="container-fluid">
        <div class="row no-gutter">
            <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
            <div class="col-md-8 col-lg-6">
                <div class="login d-flex align-items-center py-5">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-9 col-lg-8 mx-auto">
                                <h3 class="login-heading mb-4">Welcome Back!</h3>
                                <p class="mb-4">are you ready to explorer new worlds?</p>
                                <form action="{% url 'signin' %}" method="POST">
                                    {% csrf_token %}
                                    {{form|crispy}}
                                    <button
                                        class="btn btn-lg btn-success btn-block btn-login text-uppercase font-weight-bold mb-2"
                                        type="submit">singin</button>
                                    <div class="text-center">
                                        <p>Not a member yet? <a class="text-" href="{% url 'signup' %}">Signup
                                            </a>now and start reading</p>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
    </script>
</body>

</html>

library/templates/signup.html
<!doctype html>
{% load static %}

{% load crispy_forms_tags %}

<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/5a4608d316.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'auth.css' %}">

    <title>LibraryMS | Register Account</title>
</head>

<body>

    <div class="container-fluid">
        <div class="row no-gutter">
            <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
            <div class="col-md-8 col-lg-6">
                <div class="login d-flex align-items-center py-5">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-9 col-lg-8 mx-auto">
                                <h3 class="login-heading mb-4">Join us NOW!</h3>
                                <p class="mb-4">And you can read as many books as you can</p>
                                <form action="{% url 'signup' %}" method="POST">
                                    {% csrf_token %}
                                    {{form|crispy}}
                                    <button
                                        class="btn btn-lg btn-success btn-block btn-login text-uppercase font-weight-bold mb-2"
                                        type="submit">Register</button>
                                    <div class="text-center">
                                        <p>already have and account? <a class="" href="{% url 'signin' %}">signin instead</a></p>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
    </script>
</body>

</html>